// src/api/client.ts — a NEW file
// Every call to json-server lives in this one file.
import type { ApiProject, ApiSubmission, ApiUser, NewSubmission } from "../types/index";

export const API_URL = "http://localhost:3001";

export async function fetchUsers(): Promise<ApiUser[]> {
  const res = await fetch(`${API_URL}/users`);
  if (!res.ok) {
    throw new Error("Could not load users");
  }
  return res.json();
}

export async function fetchProjects(): Promise<ApiProject[]> {
  const res = await fetch(`${API_URL}/projects`);
  if (!res.ok) {
    throw new Error("Could not load projects");
  }
  return res.json();
}

export async function fetchProjectBySlug(slug: string): Promise<ApiProject> {
  const res = await fetch(`${API_URL}/projects?slug=${encodeURIComponent(slug)}`);
  if (!res.ok) {
    throw new Error("Could not load that project");
  }
  const matches: ApiProject[] = await res.json();
  if (matches.length === 0) {
    throw new Error(`No project found with slug "${slug}".`);
  }
  return matches[0];
}

// ... file continues on next slide for submissions-related functions

// src/api/client.ts — continues from the previous slide

// GET /submissions → fetch all submissions
export async function fetchSubmissions(): Promise<ApiSubmission[]> {
  const res = await fetch(`${API_URL}/submissions`);
  if (!res.ok) {
    throw new Error("Could not load submissions");
  }
  return res.json();
}

// POST /submissions → create a new submission
// Returns the saved row, including the id generated by the server
export async function createSubmission(
  newSubmission: NewSubmission
): Promise<ApiSubmission> {
  const res = await fetch(`${API_URL}/submissions`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(newSubmission),
  });
  if (!res.ok) {
    throw new Error("Could not save the submission");
  }
  return res.json();
}
